# Generated by Django 4.1 on 2022-10-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_remove_user_is_customer_remove_user_is_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('JobIDX', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Start', models.CharField(max_length=200)),
                ('Finish', models.CharField(max_length=200)),
                ('User', models.CharField(max_length=200)),
                ('Product', models.CharField(max_length=200)),
                ('File', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('Log', models.CharField(max_length=200)),
                ('ActiveCount', models.CharField(max_length=200)),
                ('Page', models.CharField(max_length=200)),
                ('Impression', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProgFile',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FILE_NAME', models.CharField(max_length=200)),
                ('PROGRAM_NAME', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FILE_NAME', models.CharField(max_length=200)),
                ('UNIQUE_NAME', models.CharField(max_length=200)),
                ('PROGRAM_NAME', models.CharField(max_length=200)),
                ('CLIENT_NAME', models.CharField(max_length=200)),
                ('JOB_TITLE', models.CharField(max_length=200)),
                ('FREQUENCY', models.CharField(choices=[('All', 'All'), ('Cycle', 'Cycle'), ('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=200)),
                ('STATUS', models.CharField(choices=[('enables', 'ENABLED'), ('disaabled', 'DISSABLED')], max_length=200)),
                ('OUT_FILE_DIRECTORY', models.CharField(max_length=200)),
            ],
        ),
    ]
