# Generated by Django 4.0.5 on 2022-10-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_history_progfile_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
