# Generated by Django 4.0.5 on 2022-10-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_alter_scheduler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
