# Generated by Django 4.1.3 on 2023-01-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_scheduler_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXEFILES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exename', models.CharField(max_length=100)),
            ],
        ),
    ]
