# Generated by Django 4.1.3 on 2023-01-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_alter_userdetail_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
